server:
  port: 1000

app:
  cors:
    allowed-origins: "http://localhost:3050"
  frontend:
    url: ${FRONTEND_URL:http://localhost:3050}
  gateway:
    url: ${GATEWAY_URL:http://localhost:1000}

spring:
  application:
    name: gateway-cloud

  config:
    import: optional:consul:/

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      config:
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true

    gateway:
      routes:
        - id: backend-service
          uri: lb://profITsoft-insurance-rest
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - TokenRelay=

        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/payments/**
          filters:
            - TokenRelay=

        - id: frontend
          uri: http://frontend:3050
          predicates:
            - Path=/**
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "${app.gateway.url}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
